# 服务器配置
server:
  #端口号
  port: 9091
  #ip
  ip: http://192.168.2.108:9091
  #工程访问上下文名称
  servlet:
    context-path: /halobiosmaintain
  # 设置session的有效时间
  session:
    timeout: 3600s

spring:
  datasource:
    druid:
      url: jdbc:mysql://47.105.120.29:3306/halobiosmaintain?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      db-type: mysql
      # 初始化 最小 最大 连接数
      initial-size: 5
      min-idle: 5
      max-active: 25
      # 获取连接时最大等待时间
      max-wait: 60000
      # 是否缓存preparedStatement，也就是PSCache。
      pool-prepared-statements: false
      # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
      max-pool-prepared-statement-per-connection-size: -1
      # 用来检测连接是否有效的sql，要求是一个查询语句，常用select 'x'。
      validation-query: SELECT 'x'
      # 单位：秒，检测连接是否有效的超时时间。
      validation-query-timeout: 1
      # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-borrow: false
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-return: false
      # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 连接保持空闲而不被驱逐的最小时间
      min-evictable-idle-time-millis: 1800000
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
    freemarker:
      cache: false    #页面不加载缓存，修改即时生效
  profiles:
    active: dev



mybatis-plus:
  mapper-locations: classpath:mybatisplus/mapper/*.xml
  type-aliases-package: com.ltmap.halobiosmaintain.entity
  configuration:
    map-underscore-to-camel-case: true


#16种excel模板下载路径
excel-template:
  biologicalQualityTemp: /excelTemplate/生物质量.xls
  fisheggQualitativeTemp: /excelTemplate/鱼卵定性.xls
  fisheggQuantitativeTemp: /excelTemplate/鱼卵定量.xls
  hydrometeorologicalTemp: /excelTemplate/水文气象.xls
  intertidalzonebiologicalQuantitativeTemp: /excelTemplate/潮间带生物定量.xls
  largezooplanktonInetTemp: /excelTemplate/浮游动物（I型网）.xls
  macrobenthosQualitativeTemp: /excelTemplate/大型底栖动物定性.xls
  macrobenthosQuantitativeTemp: /excelTemplate/大型底栖动物定量.xls
  phytoplanktonTemp: /excelTemplate/浮游植物.xls
  sedimentTemp: /excelTemplate/沉积物.xls
  sedimentgrainTemp: /excelTemplate/沉积物粒度.xls
  smallfishQualitativeTemp: /excelTemplate/仔鱼定性.xls
  smallfishQuantitativeTemp: /excelTemplate/仔鱼定量.xls
  smallzooplanktonIinetTemp: /excelTemplate/浮游动物（II型网）.xls
  swimminganimalIdentificationTemp: /excelTemplate/游泳动物.xls
  waterqualityTemp: /excelTemplate/水质.xls
  birdObserveRecordTemp: /excelTemplate/鸟类.xls
  vegetationSurveyRecordTemp: /excelTemplate/植被.xls

#excel校验相关配置
config:
  # Excel规则配置文件
  excelRules: /Config/ExcelRules/
  # Excel上传文件缓存路径（自定义）
  excelUpLoad: /Config/ExcelUpLoad/
  # Json缓存目录
  excelJson: /Config/excelJson/